name: foxglove-bridge
version: '0.7.10'
license: MIT
summary: Foxglove WebSocket bridge for ROS and ROS 2.
description: |
  High performance ROS 1 and ROS 2 WebSocket bridge using the Foxglove WebSocket protocol, written in C++.

grade: stable
confinement: strict
base: core20

source-code: https://github.com/canonical/ros-foxglove-bridge-snap
issues: https://github.com/canonical/ros-foxglove-bridge-snap/issues
contact: ubuntu-robotics-community@canonical.com
website: https://foxglove.dev/

architectures:
  - build-on: amd64
  - build-on: arm64

plugs:
  configuration-read:
    interface: content
    target: $SNAP_COMMON/configuration

apps:
  config-from-content-snap:
    command: usr/bin/config_from_content_snap.sh
    daemon: oneshot
    install-mode: disable
    before: [foxglove-bridge]
  foxglove-bridge:
    command: usr/bin/launch.sh
    daemon: simple
    plugs: [network, network-bind]
    extensions: [ros1-noetic]

  reset-config:
    command: usr/bin/reset_config.sh

parts:
  foxglove-bridge:
    plugin: catkin
    catkin-cmake-args:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCATKIN_ENABLE_TESTING=OFF
    source: https://github.com/foxglove/ros-foxglove-bridge.git
    source-tag: 0.7.10
    stage-snaps:
      - yq
    stage-packages:
      - ros-noetic-roslaunch
      # Messages definition are required to bridge them.
      # No custom message is going to be support for now
      - ros-noetic-abb-egm-msgs
      - ros-noetic-abb-rapid-msgs
      - ros-noetic-abb-rapid-sm-addin-msgs
      - ros-noetic-abb-robot-msgs
      - ros-noetic-ackermann-msgs
      - ros-noetic-actionlib-msgs
      - ros-noetic-arbotix-msgs
      - ros-noetic-aruco-msgs
      - ros-noetic-aruco-opencv-msgs
      - ros-noetic-atf-msgs
      - ros-noetic-audio-common-msgs
      - ros-noetic-automotive-autonomy-msgs
      - ros-noetic-automotive-navigation-msgs
      - ros-noetic-automotive-platform-msgs
      - ros-noetic-autoware-can-msgs
      - ros-noetic-autoware-config-msgs
      - ros-noetic-autoware-external-msgs
      - ros-noetic-autoware-lanelet2-msgs
      - ros-noetic-autoware-map-msgs
      - ros-noetic-autoware-msgs
      - ros-noetic-autoware-system-msgs
      - ros-noetic-auv-msgs
      - ros-noetic-calibration-msgs
      - ros-noetic-can-msgs
      - ros-noetic-carla-msgs
      - ros-noetic-cartesian-control-msgs
      - ros-noetic-cartesian-msgs
      - ros-noetic-clearpath-configuration-msgs
      - ros-noetic-clearpath-control-msgs
      - ros-noetic-clearpath-dock-msgs
      - ros-noetic-clearpath-localization-msgs
      - ros-noetic-clearpath-mission-manager-msgs
      - ros-noetic-clearpath-mission-scheduler-msgs
      - ros-noetic-clearpath-msgs
      - ros-noetic-clearpath-navigation-msgs
      - ros-noetic-clearpath-platform-msgs
      - ros-noetic-clearpath-safety-msgs
      - ros-noetic-clober-msgs
      - ros-noetic-cob-3d-mapping-msgs
      - ros-noetic-cob-android-msgs
      - ros-noetic-cob-control-msgs
      - ros-noetic-cob-manipulation-msgs
      - ros-noetic-cob-msgs
      - ros-noetic-cob-object-detection-msgs
      - ros-noetic-cob-perception-msgs
      - ros-noetic-common-msgs
      - ros-noetic-compass-msgs
      - ros-noetic-computer-status-msgs
      - ros-noetic-control-msgs
      - ros-noetic-controller-manager-msgs
      - ros-noetic-costmap-cspace-msgs
      - ros-noetic-cras-msgs
      - ros-noetic-create-msgs
      - ros-noetic-darknet-ros-msgs
      - ros-noetic-dataspeed-pds-msgs
      - ros-noetic-dataspeed-ulc-msgs
      - ros-noetic-dbw-fca-msgs
      - ros-noetic-dbw-mkz-msgs
      - ros-noetic-dbw-polaris-msgs
      - ros-noetic-delphi-esr-msgs
      - ros-noetic-delphi-mrr-msgs
      - ros-noetic-delphi-srr-msgs
      - ros-noetic-depthai-ros-msgs
      - ros-noetic-derived-object-msgs
      - ros-noetic-diagnostic-msgs
      - ros-noetic-diffbot-msgs
      - ros-noetic-dingo-msgs
      - ros-noetic-dwb-msgs
      - ros-noetic-dynamixel-workbench-msgs
      - ros-noetic-electronic-io-msgs
      - ros-noetic-er-public-msgs
      - ros-noetic-etsi-its-cam-msgs
      - ros-noetic-etsi-its-cam-ts-msgs
      - ros-noetic-etsi-its-cpm-ts-msgs
      - ros-noetic-etsi-its-denm-msgs
      - ros-noetic-etsi-its-msgs
      - ros-noetic-etsi-its-vam-ts-msgs
      - ros-noetic-fadecandy-msgs
      - ros-noetic-fetch-auto-dock-msgs
      - ros-noetic-fetch-driver-msgs
      - ros-noetic-fiducial-msgs
      - ros-noetic-fkie-multimaster-msgs
      - ros-noetic-flatland-msgs
      - ros-noetic-flexbe-msgs
      - ros-noetic-four-wheel-steering-msgs
      - ros-noetic-foxglove-msgs
      - ros-noetic-franka-msgs
      - ros-noetic-fuse-msgs
      - ros-noetic-gazebo-msgs
      - ros-noetic-gazebo-video-monitor-msgs
      - ros-noetic-geographic-msgs
      - ros-noetic-geometry-msgs
      - ros-noetic-gnss-info-msgs
      - ros-noetic-graph-msgs
      - ros-noetic-grasping-msgs
      # Pulls roscpp
      # - ros-noetic-grid-map-msgs
      - ros-noetic-hector-nav-msgs
      - ros-noetic-hri-actions-msgs
      - ros-noetic-hri-msgs
      - ros-noetic-husky-msgs
      - ros-noetic-ibeo-msgs
      - ros-noetic-image-exposure-msgs
      - ros-noetic-industrial-msgs
      - ros-noetic-ixblue-ins-msgs
      - ros-noetic-jackal-msgs
      - ros-noetic-jsk-common-msgs
      - ros-noetic-jsk-footstep-msgs
      - ros-noetic-jsk-gui-msgs
      - ros-noetic-jsk-hark-msgs
      - ros-noetic-jsk-recognition-msgs
      - ros-noetic-kartech-linear-actuator-msgs
      - ros-noetic-khi-robot-msgs
      - ros-noetic-kobuki-msgs
      - ros-noetic-kvh-geo-fog-3d-msgs
      - ros-noetic-led-msgs
      - ros-noetic-leo-msgs
      - ros-noetic-lgsvl-msgs
      - ros-noetic-locomotor-msgs
      - ros-noetic-map-msgs
      - ros-noetic-map-organizer-msgs
      - ros-noetic-marine-acoustic-msgs
      - ros-noetic-marine-sensor-msgs
      - ros-noetic-marker-msgs
      - ros-noetic-marti-can-msgs
      - ros-noetic-marti-common-msgs
      - ros-noetic-marti-dbw-msgs
      - ros-noetic-marti-introspection-msgs
      - ros-noetic-marti-nav-msgs
      - ros-noetic-marti-perception-msgs
      - ros-noetic-marti-sensor-msgs
      - ros-noetic-marti-status-msgs
      - ros-noetic-marti-visualization-msgs
      - ros-noetic-mavros-msgs
      - ros-noetic-mbf-msgs
      - ros-noetic-mcl-3dl-msgs
      - ros-noetic-mesh-msgs
      - ros-noetic-mia-hand-msgs
      - ros-noetic-microstrain-inertial-msgs
      - ros-noetic-mir-msgs
      - ros-noetic-mobileye-560-660-msgs
      - ros-noetic-mongodb-store-msgs
      - ros-noetic-move-base-msgs
      - ros-noetic-moveit-msgs
      - ros-noetic-moveit-task-constructor-msgs
      - ros-noetic-mpc-local-planner-msgs
      - ros-noetic-mrpt-msgs
      - ros-noetic-naoqi-bridge-msgs
      - ros-noetic-nav-2d-msgs
      - ros-noetic-nav-msgs
      - ros-noetic-nav2d-msgs
      - ros-noetic-neobotix-usboard-msgs
      - ros-noetic-neonavigation-metrics-msgs
      - ros-noetic-neonavigation-msgs
      - ros-noetic-nmea-msgs
      - ros-noetic-novatel-gps-msgs
      - ros-noetic-novatel-oem7-msgs
      - ros-noetic-object-recognition-msgs
      - ros-noetic-octomap-msgs
      - ros-noetic-open-manipulator-msgs
      - ros-noetic-p2os-msgs
      - ros-noetic-pacmod-msgs
      - ros-noetic-pal-statistics-msgs
      - ros-noetic-pcl-msgs
      - ros-noetic-pddl-msgs
      - ros-noetic-people-msgs
      - ros-noetic-phidgets-msgs
      - ros-noetic-picovoice-msgs
      - ros-noetic-pilz-msgs
      - ros-noetic-planner-cspace-msgs
      - ros-noetic-plotjuggler-msgs
      # Pulls OpenCV
      # - ros-noetic-posedetection-msgs
      - ros-noetic-power-msgs
      - ros-noetic-pr2-common-action-msgs
      - ros-noetic-pr2-controllers-msgs
      - ros-noetic-pr2-gripper-sensor-msgs
      - ros-noetic-pr2-mechanism-msgs
      - ros-noetic-pr2-msgs
      - ros-noetic-pr2-self-test-msgs
      - ros-noetic-py-trees-msgs
      - ros-noetic-qb-chain-msgs
      - ros-noetic-qb-device-msgs
      - ros-noetic-qb-softhand-industry-msgs
      - ros-noetic-radar-msgs
      - ros-noetic-rc-common-msgs
      - ros-noetic-rc-reason-msgs
      - ros-noetic-ridgeback-msgs
      - ros-noetic-rm-msgs
      - ros-noetic-robot-calibration-msgs
      - ros-noetic-robot-controllers-msgs
      - ros-noetic-robotont-msgs
      - ros-noetic-rokubimini-msgs
      - ros-noetic-ros-babel-fish-test-msgs
      - ros-noetic-rosbag-fancy-msgs
      - ros-noetic-rosbag-snapshot-msgs
      - ros-noetic-rosbridge-msgs
      - ros-noetic-rosgraph-msgs
      - ros-noetic-rosmon-msgs
      - ros-noetic-rosserial-msgs
      - ros-noetic-rtabmap-msgs
      - ros-noetic-rtcm-msgs
      - ros-noetic-safety-limiter-msgs
      - ros-noetic-schunk-svh-msgs
      - ros-noetic-sensor-msgs
      - ros-noetic-shape-msgs
      - ros-noetic-sick-safevisionary-msgs
      - ros-noetic-slam-toolbox-msgs
      - ros-noetic-smacc-msgs
      - ros-noetic-smach-msgs
      - ros-noetic-speech-recognition-msgs
      - ros-noetic-statistics-msgs
      - ros-noetic-std-msgs
      - ros-noetic-stereo-msgs
      - ros-noetic-swri-profiler-msgs
      - ros-noetic-tablet-socket-msgs
      - ros-noetic-teleop-tools-msgs
      - ros-noetic-tf2-geometry-msgs
      - ros-noetic-tf2-msgs
      - ros-noetic-tf2-sensor-msgs
      - ros-noetic-trajectory-msgs
      - ros-noetic-trajectory-tracker-msgs
      - ros-noetic-turtlebot3-autorace-msgs
      - ros-noetic-turtlebot3-msgs
      - ros-noetic-twist-mux-msgs
      - ros-noetic-ublox-msgs
      - ros-noetic-udp-msgs
      - ros-noetic-ur-dashboard-msgs
      - ros-noetic-ur-msgs
      - ros-noetic-uuid-msgs
      - ros-noetic-variant-msgs
      - ros-noetic-vector-map-msgs
      - ros-noetic-velodyne-msgs
      - ros-noetic-view-controller-msgs
      - ros-noetic-vision-msgs
      - ros-noetic-visualization-msgs
      - ros-noetic-volta-msgs
      - ros-noetic-warthog-msgs
      - ros-noetic-wfov-camera-msgs
      - ros-noetic-wireless-msgs
      - ros-noetic-xpp-msgs
      - ros-noetic-image-transport-plugins
      - ros-noetic-std-srvs

  # copy local scripts to the snap usr/bin
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/
