name: foxglove-bridge
version: '0.8.5'
license: MIT
summary: Foxglove WebSocket bridge for ROS and ROS 2.
description: |
  High performance ROS 1 and ROS 2 WebSocket bridge using the Foxglove WebSocket protocol, written in C++.

grade: stable
confinement: strict
base: core24

source-code: https://github.com/canonical/ros-foxglove-bridge-snap
issues: https://github.com/canonical/ros-foxglove-bridge-snap/issues
contact: ubuntu-robotics-community@canonical.com
website: https://foxglove.dev/

platforms:
  amd64:
  arm64:

plugs:
  configuration-read:
    interface: content
    target: $SNAP_COMMON/configuration

apps:
  config-from-content-snap:
    command: usr/bin/config_from_content_snap.sh
    daemon: oneshot
    install-mode: disable
    before: [foxglove-bridge]
  foxglove-bridge:
    command: usr/bin/launch.sh
    daemon: simple
    plugs: [network, network-bind]
    extensions: [ros2-lyrical]

  reset-config:
    command: usr/bin/reset_config.sh

parts:
  foxglove-bridge:
    plugin: colcon
    colcon-cmake-args:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTING=OFF
    source: https://github.com/foxglove/ros-foxglove-bridge.git
    source-tag: 0.8.5
    build-packages:
      - ros-lyrical-spdlog-vendor
    stage-snaps:
      - yq
    stage-packages:
      - ros-lyrical-spdlog-vendor
      - ros-lyrical-ros2launch
      # Messages definition are required to bridge them.
      # No custom message is going to be support for now
      - ros-lyrical-ackermann-msgs
      - ros-lyrical-action-msgs
      - ros-lyrical-actionlib-msgs
      - ros-lyrical-actuator-msgs
      - ros-lyrical-apriltag-msgs
      - ros-lyrical-aruco-msgs
      - ros-lyrical-aruco-opencv-msgs
      - ros-lyrical-automotive-autonomy-msgs
      - ros-lyrical-automotive-navigation-msgs
      - ros-lyrical-automotive-platform-msgs
      - ros-lyrical-autoware-auto-msgs
      - ros-lyrical-can-msgs
      - ros-lyrical-cartographer-ros-msgs
      - ros-lyrical-cascade-lifecycle-msgs
      - ros-lyrical-control-msgs
      - ros-lyrical-controller-manager-msgs
      - ros-lyrical-delphi-esr-msgs
      - ros-lyrical-delphi-mrr-msgs
      - ros-lyrical-delphi-srr-msgs
      - ros-lyrical-depthai-ros-msgs
      - ros-lyrical-derived-object-msgs
      - ros-lyrical-diagnostic-msgs
      - ros-lyrical-dwb-msgs
      - ros-lyrical-dynamixel-workbench-msgs
      - ros-lyrical-event-camera-msgs
      - ros-lyrical-flexbe-msgs
      - ros-lyrical-flir-camera-msgs
      - ros-lyrical-four-wheel-steering-msgs
      - ros-lyrical-foxglove-msgs
      - ros-lyrical-gazebo-msgs
      - ros-lyrical-geographic-msgs
      - ros-lyrical-geometry-msgs
      - ros-lyrical-gps-msgs
      - ros-lyrical-graph-msgs
      - ros-lyrical-grasping-msgs
      - ros-lyrical-grbl-msgs
      - ros-lyrical-grid-map-msgs
      - ros-lyrical-ibeo-msgs
      - ros-lyrical-irobot-create-msgs
      - ros-lyrical-kartech-linear-actuator-msgs
      - ros-lyrical-leo-msgs
      - ros-lyrical-lgsvl-msgs
      - ros-lyrical-lifecycle-msgs
      - ros-lyrical-map-msgs
      - ros-lyrical-marti-can-msgs
      - ros-lyrical-marti-common-msgs
      - ros-lyrical-marti-dbw-msgs
      - ros-lyrical-marti-introspection-msgs
      - ros-lyrical-marti-nav-msgs
      - ros-lyrical-marti-perception-msgs
      - ros-lyrical-marti-sensor-msgs
      - ros-lyrical-marti-status-msgs
      - ros-lyrical-marti-visualization-msgs
      - ros-lyrical-mavros-msgs
      - ros-lyrical-micro-ros-diagnostic-msgs
      - ros-lyrical-micro-ros-msgs
      - ros-lyrical-microstrain-inertial-msgs
      - ros-lyrical-mobileye-560-660-msgs
      - ros-lyrical-moveit-msgs
      - ros-lyrical-mrpt-msgs
      - ros-lyrical-nao-command-msgs
      - ros-lyrical-nao-sensor-msgs
      - ros-lyrical-nav-2d-msgs
      - ros-lyrical-nav-msgs
      - ros-lyrical-nav2-msgs
      - ros-lyrical-neobotix-usboard-msgs
      - ros-lyrical-nmea-msgs
      - ros-lyrical-novatel-gps-msgs
      - ros-lyrical-object-recognition-msgs
      - ros-lyrical-octomap-msgs
      - ros-lyrical-pal-statistics-msgs
      - ros-lyrical-pcl-msgs
      - ros-lyrical-pendulum-msgs
      - ros-lyrical-phidgets-msgs
      - ros-lyrical-plotjuggler-msgs
      - ros-lyrical-polygon-msgs
      - ros-lyrical-radar-msgs
      - ros-lyrical-rc-common-msgs
      - ros-lyrical-rc-reason-msgs
      - ros-lyrical-rclpy-message-converter-msgs
      - ros-lyrical-rcss3d-agent-msgs
      - ros-lyrical-realsense2-camera-msgs
      - ros-lyrical-rmf-api-msgs
      - ros-lyrical-rmf-building-map-msgs
      - ros-lyrical-rmf-charger-msgs
      - ros-lyrical-rmf-dispenser-msgs
      - ros-lyrical-rmf-door-msgs
      - ros-lyrical-rmf-fleet-msgs
      - ros-lyrical-rmf-ingestor-msgs
      - ros-lyrical-rmf-lift-msgs
      - ros-lyrical-rmf-obstacle-msgs
      - ros-lyrical-rmf-scheduler-msgs
      - ros-lyrical-rmf-site-map-msgs
      - ros-lyrical-rmf-task-msgs
      - ros-lyrical-rmf-traffic-msgs
      - ros-lyrical-rmf-visualization-msgs
      - ros-lyrical-rmf-workcell-msgs
      - ros-lyrical-robot-calibration-msgs
      - ros-lyrical-rosapi-msgs
      - ros-lyrical-rosbridge-msgs
      - ros-lyrical-rosgraph-msgs
      # Pulls OpenCV, Qt and more.
      # - ros-lyrical-rqt-image-overlay
      - ros-lyrical-rtabmap-msgs
      - ros-lyrical-rtcm-msgs
      - ros-lyrical-rviz-2d-overlay-msgs
      - ros-lyrical-sensor-msgs
      - ros-lyrical-shape-msgs
      - ros-lyrical-smach-msgs
      - ros-lyrical-soccer-vision-2d-msgs
      - ros-lyrical-soccer-vision-3d-msgs
      - ros-lyrical-soccer-vision-attribute-msgs
      - ros-lyrical-statistics-msgs
      - ros-lyrical-std-msgs
      - ros-lyrical-stereo-msgs
      - ros-lyrical-system-modes-msgs
      - ros-lyrical-teleop-tools-msgs
      - ros-lyrical-tf2-geometry-msgs
      - ros-lyrical-tf2-msgs
      - ros-lyrical-tf2-sensor-msgs
      - ros-lyrical-trajectory-msgs
      - ros-lyrical-turtlebot3-msgs
      - ros-lyrical-turtlebot4-msgs
      - ros-lyrical-twist-mux-msgs
      - ros-lyrical-ublox-msgs
      - ros-lyrical-ublox-ubx-msgs
      - ros-lyrical-udp-msgs
      - ros-lyrical-unique-identifier-msgs
      - ros-lyrical-ur-dashboard-msgs
      - ros-lyrical-ur-msgs
      - ros-lyrical-urg-node-msgs
      - ros-lyrical-velodyne-msgs
      - ros-lyrical-vision-msgs
      - ros-lyrical-visualization-msgs
      - ros-lyrical-webots-ros2-msgs
      - ros-lyrical-wiimote-msgs
      - ros-lyrical-autoware-adapi-v1-msgs
      - ros-lyrical-autoware-adapi-version-msgs
      - ros-lyrical-autoware-common-msgs
      - ros-lyrical-autoware-control-msgs
      - ros-lyrical-autoware-internal-msgs
      - ros-lyrical-autoware-localization-msgs
      - ros-lyrical-autoware-map-msgs
      - ros-lyrical-autoware-perception-msgs
      - ros-lyrical-autoware-planning-msgs
      - ros-lyrical-autoware-sensing-msgs
      - ros-lyrical-autoware-system-msgs
      - ros-lyrical-autoware-v2x-msgs
      - ros-lyrical-autoware-vehicle-msgs
      - ros-lyrical-camera-aravis2-msgs
      - ros-lyrical-create3-examples-msgs
      - ros-lyrical-data-tamer-msgs
      - ros-lyrical-dataspeed-can-msgs
      - ros-lyrical-ds-dbw-msgs
      - ros-lyrical-etsi-its-cam-msgs
      - ros-lyrical-etsi-its-cam-ts-msgs
      - ros-lyrical-etsi-its-cpm-ts-msgs
      - ros-lyrical-etsi-its-denm-msgs
      - ros-lyrical-etsi-its-msgs
      - ros-lyrical-etsi-its-vam-ts-msgs
      - ros-lyrical-ffmpeg-image-transport-msgs
      - ros-lyrical-fuse-msgs
      - ros-lyrical-marine-acoustic-msgs
      - ros-lyrical-marine-sensor-msgs
      - ros-lyrical-mola-msgs
      - ros-lyrical-nao-lola-command-msgs
      - ros-lyrical-nao-lola-sensor-msgs
      - ros-lyrical-ouster-sensor-msgs
      - ros-lyrical-ros-babel-fish-test-msgs
      - ros-lyrical-ros2-socketcan-msgs
      - ros-lyrical-rosbag2-performance-benchmarking-msgs
      - ros-lyrical-rosbridge-test-msgs
      - ros-lyrical-service-msgs
      - ros-lyrical-soccer-geometry-msgs
      - ros-lyrical-soccer-model-msgs

  # copy local scripts to the snap usr/bin
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/
