name: foxglove-bridge
version: '0.8.0'
license: MIT
summary: Foxglove WebSocket bridge for ROS and ROS 2.
description: |
  High performance ROS 1 and ROS 2 WebSocket bridge using the Foxglove WebSocket protocol, written in C++.

grade: stable
confinement: strict
base: core24

source-code: https://github.com/canonical/ros-foxglove-bridge-snap
issues: https://github.com/canonical/ros-foxglove-bridge-snap/issues
contact: ubuntu-robotics-community@canonical.com
website: https://foxglove.dev/

platforms:
  amd64:
  arm64:

plugs:
  configuration-read:
    interface: content
    target: $SNAP_COMMON/configuration

apps:
  config-from-content-snap:
    command: usr/bin/config_from_content_snap.sh
    daemon: oneshot
    install-mode: disable
    before: [foxglove-bridge]
  foxglove-bridge:
    command: usr/bin/launch.sh
    daemon: simple
    plugs: [network, network-bind]
    extensions: [ros2-jazzy]

  reset-config:
    command: usr/bin/reset_config.sh

parts:
  foxglove-bridge:
    plugin: colcon
    colcon-cmake-args:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTING=OFF
    source: https://github.com/foxglove/ros-foxglove-bridge.git
    source-tag: 0.8.0
    build-packages:
      - ros-jazzy-spdlog-vendor
    stage-snaps:
      - yq
    stage-packages:
      - ros-jazzy-spdlog-vendor
      - ros-jazzy-ros2launch
      # Messages definition are required to bridge them.
      # No custom message is going to be support for now
      - ros-jazzy-ackermann-msgs
      - ros-jazzy-action-msgs
      - ros-jazzy-actionlib-msgs
      - ros-jazzy-actuator-msgs
      - ros-jazzy-apriltag-msgs
      - ros-jazzy-aruco-msgs
      - ros-jazzy-aruco-opencv-msgs
      - ros-jazzy-automotive-autonomy-msgs
      - ros-jazzy-automotive-navigation-msgs
      - ros-jazzy-automotive-platform-msgs
      - ros-jazzy-autoware-auto-msgs
      - ros-jazzy-can-msgs
      - ros-jazzy-cartographer-ros-msgs
      - ros-jazzy-cascade-lifecycle-msgs
      - ros-jazzy-control-msgs
      - ros-jazzy-controller-manager-msgs
      - ros-jazzy-delphi-esr-msgs
      - ros-jazzy-delphi-mrr-msgs
      - ros-jazzy-delphi-srr-msgs
      - ros-jazzy-depthai-ros-msgs
      - ros-jazzy-derived-object-msgs
      - ros-jazzy-diagnostic-msgs
      - ros-jazzy-dwb-msgs
      - ros-jazzy-dynamixel-workbench-msgs
      - ros-jazzy-event-camera-msgs
      - ros-jazzy-flexbe-msgs
      - ros-jazzy-flir-camera-msgs
      - ros-jazzy-four-wheel-steering-msgs
      - ros-jazzy-foxglove-msgs
      - ros-jazzy-gazebo-msgs
      - ros-jazzy-geographic-msgs
      - ros-jazzy-geometry-msgs
      - ros-jazzy-gps-msgs
      - ros-jazzy-graph-msgs
      - ros-jazzy-grasping-msgs
      - ros-jazzy-grbl-msgs
      - ros-jazzy-grid-map-msgs
      - ros-jazzy-ibeo-msgs
      - ros-jazzy-irobot-create-msgs
      - ros-jazzy-kartech-linear-actuator-msgs
      - ros-jazzy-leo-msgs
      - ros-jazzy-lgsvl-msgs
      - ros-jazzy-lifecycle-msgs
      - ros-jazzy-map-msgs
      - ros-jazzy-marti-can-msgs
      - ros-jazzy-marti-common-msgs
      - ros-jazzy-marti-dbw-msgs
      - ros-jazzy-marti-introspection-msgs
      - ros-jazzy-marti-nav-msgs
      - ros-jazzy-marti-perception-msgs
      - ros-jazzy-marti-sensor-msgs
      - ros-jazzy-marti-status-msgs
      - ros-jazzy-marti-visualization-msgs
      - ros-jazzy-mavros-msgs
      - ros-jazzy-micro-ros-diagnostic-msgs
      - ros-jazzy-micro-ros-msgs
      - ros-jazzy-microstrain-inertial-msgs
      - ros-jazzy-mobileye-560-660-msgs
      - ros-jazzy-moveit-msgs
      - ros-jazzy-mrpt-msgs
      - ros-jazzy-nao-command-msgs
      - ros-jazzy-nao-sensor-msgs
      - ros-jazzy-nav-2d-msgs
      - ros-jazzy-nav-msgs
      - ros-jazzy-nav2-msgs
      - ros-jazzy-neobotix-usboard-msgs
      - ros-jazzy-nmea-msgs
      - ros-jazzy-novatel-gps-msgs
      - ros-jazzy-object-recognition-msgs
      - ros-jazzy-octomap-msgs
      - ros-jazzy-pal-statistics-msgs
      - ros-jazzy-pcl-msgs
      - ros-jazzy-pendulum-msgs
      - ros-jazzy-phidgets-msgs
      - ros-jazzy-plotjuggler-msgs
      - ros-jazzy-polygon-msgs
      - ros-jazzy-radar-msgs
      - ros-jazzy-rc-common-msgs
      - ros-jazzy-rc-reason-msgs
      - ros-jazzy-rclpy-message-converter-msgs
      - ros-jazzy-rcss3d-agent-msgs
      - ros-jazzy-realsense2-camera-msgs
      - ros-jazzy-rmf-api-msgs
      - ros-jazzy-rmf-building-map-msgs
      - ros-jazzy-rmf-charger-msgs
      - ros-jazzy-rmf-dispenser-msgs
      - ros-jazzy-rmf-door-msgs
      - ros-jazzy-rmf-fleet-msgs
      - ros-jazzy-rmf-ingestor-msgs
      - ros-jazzy-rmf-lift-msgs
      - ros-jazzy-rmf-obstacle-msgs
      - ros-jazzy-rmf-scheduler-msgs
      - ros-jazzy-rmf-site-map-msgs
      - ros-jazzy-rmf-task-msgs
      - ros-jazzy-rmf-traffic-msgs
      - ros-jazzy-rmf-visualization-msgs
      - ros-jazzy-rmf-workcell-msgs
      - ros-jazzy-robot-calibration-msgs
      - ros-jazzy-rosapi-msgs
      - ros-jazzy-rosbridge-msgs
      - ros-jazzy-rosgraph-msgs
      # Pulls OpenCV, Qt and more.
      # - ros-jazzy-rqt-image-overlay
      - ros-jazzy-rtabmap-msgs
      - ros-jazzy-rtcm-msgs
      - ros-jazzy-rviz-2d-overlay-msgs
      - ros-jazzy-sensor-msgs
      - ros-jazzy-shape-msgs
      - ros-jazzy-smach-msgs
      - ros-jazzy-soccer-vision-2d-msgs
      - ros-jazzy-soccer-vision-3d-msgs
      - ros-jazzy-soccer-vision-attribute-msgs
      - ros-jazzy-statistics-msgs
      - ros-jazzy-std-msgs
      - ros-jazzy-stereo-msgs
      - ros-jazzy-system-modes-msgs
      - ros-jazzy-teleop-tools-msgs
      - ros-jazzy-tf2-geometry-msgs
      - ros-jazzy-tf2-msgs
      - ros-jazzy-tf2-sensor-msgs
      - ros-jazzy-trajectory-msgs
      - ros-jazzy-turtlebot3-msgs
      - ros-jazzy-turtlebot4-msgs
      - ros-jazzy-twist-mux-msgs
      - ros-jazzy-ublox-msgs
      - ros-jazzy-ublox-ubx-msgs
      - ros-jazzy-udp-msgs
      - ros-jazzy-unique-identifier-msgs
      - ros-jazzy-ur-dashboard-msgs
      - ros-jazzy-ur-msgs
      - ros-jazzy-urg-node-msgs
      - ros-jazzy-velodyne-msgs
      - ros-jazzy-vision-msgs
      - ros-jazzy-visualization-msgs
      - ros-jazzy-webots-ros2-msgs
      - ros-jazzy-wiimote-msgs
      - ros-jazzy-autoware-adapi-v1-msgs
      - ros-jazzy-autoware-adapi-version-msgs
      - ros-jazzy-autoware-common-msgs
      - ros-jazzy-autoware-control-msgs
      - ros-jazzy-autoware-internal-msgs
      - ros-jazzy-autoware-localization-msgs
      - ros-jazzy-autoware-map-msgs
      - ros-jazzy-autoware-perception-msgs
      - ros-jazzy-autoware-planning-msgs
      - ros-jazzy-autoware-sensing-msgs
      - ros-jazzy-autoware-system-msgs
      - ros-jazzy-autoware-v2x-msgs
      - ros-jazzy-autoware-vehicle-msgs
      - ros-jazzy-camera-aravis2-msgs
      - ros-jazzy-create3-examples-msgs
      - ros-jazzy-data-tamer-msgs
      - ros-jazzy-dataspeed-can-msgs
      - ros-jazzy-ds-dbw-msgs
      - ros-jazzy-etsi-its-cam-msgs
      - ros-jazzy-etsi-its-cam-ts-msgs
      - ros-jazzy-etsi-its-cpm-ts-msgs
      - ros-jazzy-etsi-its-denm-msgs
      - ros-jazzy-etsi-its-msgs
      - ros-jazzy-etsi-its-vam-ts-msgs
      - ros-jazzy-ffmpeg-image-transport-msgs
      - ros-jazzy-fuse-msgs
      - ros-jazzy-marine-acoustic-msgs
      - ros-jazzy-marine-sensor-msgs
      - ros-jazzy-mola-msgs
      - ros-jazzy-nao-lola-command-msgs
      - ros-jazzy-nao-lola-sensor-msgs
      - ros-jazzy-ouster-sensor-msgs
      - ros-jazzy-ros-babel-fish-test-msgs
      - ros-jazzy-ros2-socketcan-msgs
      - ros-jazzy-rosbag2-performance-benchmarking-msgs
      - ros-jazzy-rosbridge-test-msgs
      - ros-jazzy-service-msgs
      - ros-jazzy-soccer-geometry-msgs
      - ros-jazzy-soccer-model-msgs

  # copy local scripts to the snap usr/bin
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/
