name: snap
on:
  push:
    tags:
      - 'jazzy/*'
    branches:
      - jazzy
  pull_request:
    branches:
      - jazzy
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  snaps:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      snapcraft-enable-experimental-extensions: true
      runs-on: '["ubuntu-latest", ["self-hosted", "linux", "ARM64", "medium", "noble"]]'
      snap-track: jazzy
