name: snap
on:
  push:
    tags:
      - 'humble/*'
    branches:
      - humble
  pull_request:
    branches:
      - humble
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  snaps:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      runs-on: '["ubuntu-latest", ["self-hosted", "linux", "ARM64", "medium", "noble"]]'
      snap-track: '${{ github.base_ref || github.ref_name }}'
